### ISSUE TITLE
Solr 5.0

### ISSUE THREAD

**Issue by Bangsheng** [NGDATA/hbase-indexer#61]
The documents says the hbase-indexer supports solr 4.x. But the documents were created two years ago. So I am wondering whether I can use the newest hbase-indexer for solr 5.0. If not, may I know what is the newest version of hbase and solr that is supported?

I tried to setup hbase-indexer using hbase 0.98.11 and solr 5.0.0, but failed. So I think the first thing I need to make sure is the version of hbase and solr.

**Comment by gabrielreid** [comment]
Solr 4.4.0 is the most recent version that hbase-indexer is developed and tested against. We haven't yet looked into porting it to Solr 5, but if you'd like to look into this and possibly submit a patch for needed changes that would be great.

**Comment by Bangsheng** [comment]
Thanks, Gabriel.

May I know whether 0.98.6 is the most recent hbase that is supported? I think I need to set up a working cluster first before I test newer versions.

**Comment by gabrielreid** [comment]
0.98.6 is the most recent version that will work with certainty (note that this is the CDH variant of 0.98). Newer 0.98.x versions will also likely work, but I can't guarantee that.

**Comment by Bangsheng** [comment]
I am runnint Hbase 0.98.11 and Solr 4.10 now. I got the this error:

Incorrect header or version mismatch from ip:37340 got version 0 expected version 3.

May I know whether it is complaining about the version of Hbase or Solr?

**Comment by Bangsheng** [comment]
I changed the HBase version to 0.98.6-hadoop2 and I still got the same error. So I stopped Solr, but still have the same error. I was expecting some other error like 'fail to connect to Solr'. Now I am confused.  I checked the jar files I copied to Hbase/lib from hbase-indexer-1.6-SNAPSHOT/lib. There are actually four jars instead of 2 and one of them named hbase-sep-impl-1.6-hbase0.94-SNAPSHOT.jar. There is no jar named as *hbase-0.96*. I am wondering whether I should use hbase 0.94.

**Comment by Bangsheng** [comment]
I just noticed that in order to build for HBase 0.98, I need add -Dhbase.api=0.98. Now the hbase-indexer seems to work fine with 0.98.6 here. And I received the error from hbase-indexer

java.lang.RuntimeException: org.apache.solr.common.SolrException: Unknown document router '{name=implicit}'

It is said this error is caused by incompatible version of Solr and SolrJ. So I switch Solr to 4.4.0. However, I get the same error as hbase-indexer when I try to start Solr 4.4.0 as cloud mode. I have been working on this for a while, but still can't get it solved. Do you have any idea?

**Comment by Bangsheng** [comment]
I removed all the files of Solr from Zookeeper and restart solr again. It works now.

**Comment by jeremy-huang** [comment]
When i put one record to hbase like this: 
-> put 'indexdemo-user', 'row1', 'info:firstname', 'Jim'

I got two row info from hbase-indexer:

INFO cloud.ConnectionManager: Client is connected to ZooKeeper
INFO cloud.ZkStateReader: Updating cluster state from ZooKeeper...

block there.

But solr print log show it seems add document success like this:

7754869 [qtp19313191-18] INFO  org.apache.solr.update.processor.LogUpdateProcessor  – [collection1] webapp=/solr path=/update params={wt=javabin&version=2} {add=[row1 (1499038416479715328)]} 0 1

7769870 [commitScheduler-7-thread-1] INFO  org.apache.solr.update.UpdateHandler  – start commit{,optimize=false,openSearcher=false,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}

7769891 [commitScheduler-7-thread-1] INFO  org.apache.solr.core.SolrCore  – SolrDeletionPolicy.onCommit: commits: num=2
        commit{dir=NRTCachingDirectory(org.apache.lucene.store.MMapDirectory@/home/hduser/app/solr-4.4.0/example/solr/collection1/data/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@474b8734; maxCacheMB=48.0 maxMergeSizeMB=4.0),segFN=segments_6,generation=6}
        commit{dir=NRTCachingDirectory(org.apache.lucene.store.MMapDirectory@/home/hduser/app/solr-4.4.0/example/solr/collection1/data/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@474b8734; maxCacheMB=48.0 maxMergeSizeMB=4.0),segFN=segments_7,generation=7}

7769892 [commitScheduler-7-thread-1] INFO  org.apache.solr.core.SolrCore  – newest commit generation = 7

7769898 [commitScheduler-7-thread-1] INFO  org.apache.solr.search.SolrIndexSearcher  – Opening Searcher@29822ba9 realtime

7769900 [commitScheduler-7-thread-1] INFO  org.apache.solr.update.UpdateHandler  – end_commit_flush


I can not query any info from solr.

I build for HBase 0.98, the version solr 4.4.0,solrj 4.4.0

**Comment by gabrielreid** [comment]
Could you be more specific on what you mean that you cannot query any info from Solr? Is Solr showing that the index is empty, or is your query on Solr failing? How are you running your query on Solr?

**Comment by gabrielreid** [comment]
And even better, could you follow this up on the user mailing list referenced here: http://ngdata.github.io/hbase-indexer/

This ticket is an issue about using an unsupported version of Solr, and it looks like you've got a general support question which would be better handled on the user mailing list.

**Comment by jeremy-huang** [comment]
Thanks, Gabriel
It's my mistake for setting solr configuration,now, Hbase-Indexer is work.

Hope to support solr5.0 as soon as possible.thks
