### ISSUE TITLE
run hbase-indexer server as daemon in Ubuntu

### ISSUE THREAD

**Issue by Bangsheng** [NGDATA/hbase-indexer#62]
Hi,

May I know how to run hbase-indexer server as daemon in Ubuntu?

**Comment by Bangsheng** [comment]
Aha! I looked into the hbase-indexer under bin folder and I found the solution. Just run as bin/hbase-indexer daemon.

**Comment by gabrielreid** [comment]
@Bangsheng in the future, for questions like this can you post on the user mailing list (linked to from the [hbase-indexer page](http://ngdata.github.io/hbase-indexer/)) instead of opening issues here?

**Comment by Bangsheng** [comment]
@gabrielreid Sorry, I didn't know there was a mailing list. I found this only place where I can post questions about hbase-indexer. And people could find answers here easily if they have same problems as me because this should be first place we would look into when we have a problem using the project. Maybe I was wrong. I will use mailing list if I have similar questions later.

Thanks again for your awesome work. The hbase-indexer works perfectly now in my cluster.
