### ISSUE TITLE
hbase-indexer with option -cp solr.zk=... will ignore values other than localhost:2181/solr

### ISSUE THREAD

**Issue by siom79** [NGDATA/hbase-indexer#63]
The [tutorial](https://github.com/NGDATA/hbase-indexer/wiki/Tutorial) explains that you can pass the zookeeper connection string using the option `-cp solr.zk=...`. Passing here a value different than localhost:2181 will cause the value to be ignored:
```
bin/hbase-indexer.sh add-indexer -n myindexer -c ../indexdemo-indexer.xml --cp solr.zk=localhost:9983 --cp solr.collection=collection1

ZooKeeper connection string not specified, using default: localhost:2181
```
Using the option `-z` instead will always append `/solr`:
```
bin/hbase-indexer.sh add-indexer -n myindexer -c ../indexdemo-indexer.xml -z localhost:9983 --cp solr.collection=collection1

WARNING: no -cp solr.zk specified, will use localhost:9983/solr
```
Background: I am running Solr with `bin/solr start -e cloud -noprompt`. This lets Solr start an embedded zookeeper at `localhost:9983` with the directory structure in the root directory `/` instead of `/solr`.

**Comment by siom79** [comment]
Meanwhile I have found out that the option `-z` is used for the hbase-indexer zookeeper connection and `-cp solr.zk ...` for the Solr zookeeper connection string.

**Comment by gabrielreid** [comment]
Good to hear you got this figured out -- sorry I wasn't able to get back to you on it earlier.

**Comment by siom79** [comment]
Maybe you improve the output for the two cases above a little bit, as the warning `ZooKeeper connection string not specified, using default: localhost:2181` irriates when you specify the option `-cp solr.zk=...`.

**Comment by kanav-narula** [comment]
Hi,

I am able to start hbase-indexer with external zookeeper. but while integrating with solr, I am getting the below issue.
I am using the below command for solr integration with zookeeper.

#### bin/solr start -e cloud -noprompt -z  IP:2181 ####


``` 
{msg=SolrCore 'gettingstarted_shard1_replica2' is not available due to init failure: Could not find configName for collection gettingstarted found:null,trace=org.apache.solr.common.SolrException: SolrCore 'gettingstarted_shard1_replica2' is not available due to init failure: Could not find configName for collection gettingstarted found:null

Caused by: org.apache.solr.common.cloud.ZooKeeperException: Could not find configName for collection gettingstarted found:null
```
