### ISSUE TITLE
 Lily Hbase Indexers always auto exit 

### ISSUE THREAD

**Issue by geosmart** [NGDATA/hbase-indexer#66]
with cdh ,i want to generate hbase secondary index with hbase-indexer,
I do it like these:
#### generate solr collection
``` shell
solrctl instancedir --create User  $HOME/hbase-indexer/User 
solrctl collection --create User
```
####  edit morphline-hbase-mapper.xml
```  xml
<?xml version="1.0"?> 
<indexer table="User" mapper="com.ngdata.hbaseindexer.morphline.MorphlineResultToSolrMapper"> 
   <param name="morphlineFile" value="morphlines.conf"/> 
   <!-- The optional morphlineId identifies a morphline if there are multiple morphlines in morphlines.conf -->
   <!-- <param name="morphlineId" value="userMap"/>-->
</indexer>
```
#### in the cloudera manager UI config the `morphlines.conf `
```json
SOLR_LOCATOR : {
  # Name of solr collection
  collection : collection
 
  # ZooKeeper ensemble
  zkHost : "$ZK_HOST"
}


morphlines : [
{
id : userMap
importCommands : ["org.kitesdk.**", "com.ngdata.**"]

commands : [                   
  {
    extractHBaseCells {
      mappings : [
        {
          inputColumn : "data:name"
          outputField : "name"
          type : string
          source : value
        },
        {
          inputColumn : "data:psd"
          outputField : "psd"
          type : string
          source : value
        },
        {
          inputColumn : "data:address"
          outputField : "address"
          type : string
          source : value
        },
        {
          inputColumn : "data:photo"
          outputField : "photo"
          type : string
          source : value
        }
      ]
    }
  }


  { logDebug { format : "output record: {}", args : ["@{}"] } }
]
}
]
``` 
####  hbase-indexer config 
``` shell
hbase-indexer add-indexer \
--name userIndexer \
--indexer-conf $HOME/hbase-indexer/morphline-hbase-mapper.xml \
--connection-param solr.zk=server1:2181/solr \
--connection-param solr.collection=User \
--zookeeper server1:2181
```

#### in the `hbase shell`,wirte data
```
``` shell 
create 'User', {NAME => 'data', REPLICATION_SCOPE => 1}   
put 'User','row2','data:name','u2'
put 'User','row2','data:psd','123'   
put 'User','row2','data:address','address2'   
put 'User','row2','data:photo','photo2'    
```

#### and then hbase-indexer exit ,here is the [gist  log detail ](https://gist.github.com/geosmart/c70a9bc4ed97d95b9c8e)

the problem drive me crazy,have puzzled me a lot days, anyhelp will be appreciate

**Comment by geosmart** [comment]
just like this question [lily-hbase-indexers-exit-for-no-reason](http://www.tagwith.com/question_781662_lily-hbase-indexers-exit-for-no-reason)

**Comment by gabrielreid** [comment]
If that is the full log of hbase-indexer when the process exits (like in the additional link that you posted), then hbase-indexer process is being killed by something external, most likely by the operating system due to low memory (if the indexer process has indeed stopped).

Take a look in your system log (probably /var/log/messages) to see if there is an entry from the OOM killer killing your process.

What is the heap size being allocated for the indexer process?

**Comment by geosmart** [comment]
@gabrielreid ,thanks for you reply!!!
I clear the log in `/var/log/messages`,and  reCreate the Solr collection and instancedir ,reAdd the hbase-indexer (-name userIndexer),then input data  to hbase to test what make it exit!

Now the hbase-indexer exit with this situation:
*  Input data to hbase,and solr add the doc,  the hbase-indexer work !
*  When I do Batch insert with Hbase JavaAPI,Solr only input 8 docs,then  hbase-indexer exit with no reason(ast least I don't know why so far),  Last Time I run the batch insert  testcase,it input 250 docs  to Solr then  hbase-indexer  exit.

*  I checked `/var/log/messages`,it is empty!
*  System  have enough memorry,therer are 4G memery are free  !
Is there somewhere to config the hbase-indexer max memorry size (like JVM Xmx)?

**Comment by gabrielreid** [comment]
The location of logging information about the OOM killer will depend on which OS version that you're using. 

When you say that there is 4 GB of free memory on your system, is that before or after the process exits?

You should be able to configure the environment variable of HBASE_INDEXER_HEAPSIZE in Cloudera Manager, although I can't directly say where that is (there's a "safety-valve setting on the hbase-indexer process in CM where you can set environment variables in Cloudera Manager).

Another option is to just start hbase-indexer server up manually in a terminal window and see what happens (and check the exit code when you do that). That's just a question of running the following command:

    hbase-indexer server

**Comment by geosmart** [comment]
You are right! The OOM make it exit!
1. I make sure it is the OOM make it exit in this file::
``` shell
# cat /opt/cm/run/cloudera-scm-agent/process/148 ks_indexer-HBASE_INDEXER/logs/stdout.log
Sun Oct 25 20:14:58 CST 2015
JAVA_HOME=/usr/java/jdk1.7.0_80
using 5 as CDH_VERSION

# java.lang.OutOfMemoryError: Java heap space
# -XX:OnOutOfMemoryError="kill -9 %p"
#   Executing /bin/sh -c "kill -9 2434"...
```
2. I run 'hbase-indexer server' ,the indexer  can generate  and without exit;
3. I have not found the environment variable of `HBASE_INDEXER_HEAPSIZE` in Cloudera Manager(version 5.4.7),but found a variable of 'Java Heap Size of Lily HBase Indexer in Bytes'(
Maximum size in bytes for the Java Process heap memory. Passed to Java -Xmx.),i change the Lily HBase Indexer Default Group from 131M to 1GiB
3. restart the  Key-Value Store Indexer ,and input some rows, now hbase indexer not exit!

@gabrielreid  the problem turned out is a normal OOM ,very easy,but when it is not resolved,it is always a problem Thanks you very much ! 

At last, upload some screenshoots to celebrate the the Good Health of Key-Value Store Indexer! 

* heap size config
![heap size config](https://raw.githubusercontent.com/geosmart/geosmart.io/master/source/_posts/2015/09/%E5%9F%BA%E4%BA%8ESolr%E7%9A%84Hbase%E4%BA%8C%E7%BA%A7%E7%B4%A2%E5%BC%95/heapsize.png)

* hbase indexer
![hbase indexer](https://raw.githubusercontent.com/geosmart/geosmart.io/master/source/_posts/2015/09/%E5%9F%BA%E4%BA%8ESolr%E7%9A%84Hbase%E4%BA%8C%E7%BA%A7%E7%B4%A2%E5%BC%95/hbaseindexer.png)


* solr index
![solr index](https://raw.githubusercontent.com/geosmart/geosmart.io/master/source/_posts/2015/09/%E5%9F%BA%E4%BA%8ESolr%E7%9A%84Hbase%E4%BA%8C%E7%BA%A7%E7%B4%A2%E5%BC%95/solr.png)

**Comment by gabrielreid** [comment]
Good to hear you got it resolved, thanks for posting it back up here.
