### ISSUE TITLE
Error: Could not find or load main class com.ngdata.hbaseindexer.cli.AddIndexerCli

### ISSUE THREAD

**Issue by ezhilrean** [NGDATA/hbase-indexer#76]
I am trying out the hbase solr integration using the hbase indexer in Hadoop ecosystem. The problem i face is that i dont see the require jars provided in the hbase indexer git hub site. I can see the CDH has all the required jars for hbase indexer within the package. Can you please help me in getting the jars. I get error like class not found AddIndexerCli

**Comment by gabrielreid** [comment]
The github site only provides the source code for hbase-indexer. You'll need to build the jars yourself, using [Apache Maven](https://maven.apache.org). Instructions on building the project are included in the top-level [README](https://github.com/NGDATA/hbase-indexer/blob/master/README.md) file of the project
