### ISSUE TITLE
Fail to Authenticate when using with secure solr with kerberos

### ISSUE THREAD

**Issue by parveenb1** [NGDATA/hbase-indexer#95]
Hi
i have getting issue when I am using hbase-indexer with secure solr using KERBEROS 
i have added keytab file in hbase-indexer-site.xml but its still not authorized to access solr

cloud.ConnectionManager: Watcher org.apache.solr.common.cloud.ConnectionManager@1ee44ef7 name:ZooKeeperConnection Watcher:server1:2181/solr got event WatchedEvent state:SaslAuthenticated type:None path:null path:null type:None
17/02/22 14:26:15 ERROR impl.CloudSolrClient: Request to collection hbaseindex failed due to (401) org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://server1:8983/solr/hbaseindex_shard1_replica1: Expected mime type application/octet-stream but got text/html. <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 401 Authentication required</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /solr/hbaseindex_shard1_replica1/update. Reason:
<pre>    Authentication required</pre></p>
</body>
</html>

**Comment by QilinCao** [comment]
When using with secure solr5.5 or solr6.3 with kerberos, you should use httpclient-4.4.x,  and add -Djava.security.auth.login.config=${HBASEINDEXER_CONF_DIR}/jaas.conf to your java process. Furthermore, a few code should be added as follows:
        HttpClientUtil.setConfigurer(new Krb5HttpClientConfigurer());
This problem is resolved by solr6.5, is a solrj issue.
